[mypy]
python_version = 3.11
strict = True
warn_unused_configs = True
warn_unreachable = True
warn_redundant_casts = True
warn_return_any = True
no_implicit_reexport = True
disallow_any_generics = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = True
no_implicit_optional = True
show_error_codes = True
show_column_numbers = True
pretty = True
files = src/resilience_kit

[mypy-tests.*]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-pybreaker.*]
ignore_missing_imports = True

[mypy-testcontainers.*]
ignore_missing_imports = True

[mypy-asyncpg.*]
ignore_missing_imports = True
